Lesse here ...
AspenWeb/aspen.py pull request #36
Opened 2016-09-15 19:02 UTC by whit537

Next doc PR, after #35.

2016-09-15 20:55 UTC, whit537 commented
Ready for review, @Changaco.

2016-09-15 22:19 UTC, Changaco requested changes
You can't remove the `repr` decode strategy, we use it in both aspen and pando.

2016-09-15 22:25 UTC, Changaco reviewed
Just because we can doesn't necessarily mean we should. This change means we have to release a new version of the aspen-jinja package, unless you're planning to integrate the Jinja renderer directly in Aspen?

2016-09-15 22:26 UTC, Changaco commented
(I'm going to sleep now.)

2016-09-15 23:27 UTC, whit537 commented on docs/reference/index.rst
> -:py:mod:`~aspen.configuration`, :py:mod:`~aspen.exceptions`, and
Foo bar

2016-09-15 23:40 UTC, whit537 commented
Hmm ... I'm adjusting to the new GitHub PR review UI. Is there no link between your comments and the relevant lines?

2016-09-15 23:48 UTC, whit537 commented
> we have to release a new version of the aspen-jinja package

Hmm ... good point. Also `aspen-pystache` and `aspen-tornado`. That's not that hard, is it? :-)

We should at least issue a deprecation warning in 1.0 saying that `aspen.renderers` will go away in 2.0.

> we use it in both aspen and pando.

Sorry ... where?

2016-09-16 07:54 UTC, Changaco commented
> Hmm ... I'm adjusting to the new GitHub PR review UI. Is there no link between your comments and the relevant lines?

Apparently not, maybe I'm using it wrong though.

> That's not that hard, is it? :-)

No, but it's still time we wouldn't be spending on more useful stuff.

> We should at least issue a deprecation warning in 1.0 saying that `aspen.renderers` will go away in 2.0.

I'm okay with that.

> Sorry ... where?

`git grep "'repr'"`

2016-09-17 12:54 UTC, whit537 commented
> I'm okay with that.

Ready for review in 66b690cbd5a2b9fb1381133cc503db2207b02dc7.

> You can't remove the `repr` decode strategy, we use it in both aspen and pando.

How about efa830a21e38db2c421a722e63745de6ddfeaf44?

2016-09-17 15:32 UTC, whit537 commented
I've reworked the doc structure and written a first draft of the dispatch doc. I'm keeping it on the `docs` branch for now. If I get all that written before we land this then I'll maybe make a separate branch.

![screen shot 2016-09-17 at 11 31 26 am](https://cloud.githubusercontent.com/assets/134455/18609205/65a12310-7cca-11e6-8715-97d1d2cef640.png)

2016-09-17 22:03 UTC, whit537 commented
I've got a draft of "How to Write a Simplate" and half of "How to Write a Plugin." Going afk for a while.

2016-09-18 09:10 UTC, Changaco approved these changes

2016-09-18 09:11 UTC, merged